export enum AlertType {
  TENANT_INSURANCE_EXPIRED = "TNT_INS_EXP",
  EMPLOYEE_CONTRACT_EXPIRED = 'EMP_CONTRACT_EXP',
  DRIVER_LICENCE_EXPIRED = 'DRI_LICENCE_EXP',
  PROFESSIONAL_DRIVER_LICENCE_EXPIRED = 'PRO_DRI_LICENCE_EXP',
  DRIVER_VISA_EXPIRED = 'DRI_VISA_EPX',
  DRIVER_MEDICAL_EXAMINATION_EXPIRED = 'DRI_MED_EXAM_EXP',
  VEHICLE_REGISTRATION_EXPIRED = 'VEH_REG_EXP',
  VEHICLE_TECHNICAL_INSPECTION_EXPIRED = 'VEH_TECH_EXP',
  VEHICLE_ADR_EXPIRED = 'VEH_ADR_EXP',
  VEHICLE_FIRE_EXTINGUISHER_CHECK_EXPIRED = 'VEH_FIRE_EXP',
  VEHICLE_TACHOGRAPH_EXPIRED = 'VEH_TACHO_EXP',
  DRIVER_ADR_EXPIRED = "DRI_ADR_EXP",
  DRIVER_GOV_ID_EXPIRED = "DRI_GOV_ID_EXP",
  DRIVER_CODE_95_EXPIRED = "DRI_CODE_95_EXP",
  DRIVER_TACHOGRAPH_CARD_EXPIRED = "DRI_TACHO_CARD_EXP",
  VEHICLE_MANDATORY_INSURANCE_EXPIRED = "VEH_MAN_INS_EXP",
  VEHICLE_OPTIONAL_INSURANCE_EXPIRED = "VEH_OPT_INS_EXP",
  VEHICLE_SMALL_SERVICE_EXPIRED = "VEH_SMALL_SER_EXP",
  VEHICLE_BIG_SERVICE_EXPIRED = "VEH_BIG_SER_EXP",
  VEHICLE_PERIODICAL_TECHNICAL_INSPECTION_EXPIRED = "VEH_PER_TECH_EXP",
  VEHICLE_TIRES_REPLACEMENT_EXPIRED = "VEH_TIRES_REPLACE_EXP",
  VEHICLE_LEASING_EXPIRED = "VEH_LEASING_EXP"
}

export interface Alert {
  id: string;
  ruleName: AlertType;
  alertable: any;
}
