import { PositionEnum } from '@/lib/api/employees.d';
import type { RadioOption } from '@/ui';
import keyBy from 'lodash/keyBy';

interface PositionOption {
  label: string;
  value: PositionEnum;
}

export const positionLabelMap = {
  [PositionEnum.Ceo]: 'CEO',
  [PositionEnum.Manager]: 'Menadžer',
  [PositionEnum.Dispatcher]: 'Disponent',
  [PositionEnum.Driver]: 'Vozač',
};

export const positionOptions: PositionOption[] = [
  { label: 'CEO', value: PositionEnum.Ceo },
  { label: 'Menadžer', value: PositionEnum.Manager },
  { label: 'Disponent', value: PositionEnum.Dispatcher },
  { label: 'Vozač', value: PositionEnum.Driver },
];

export const genderOptions: RadioOption[] = [
  { label: 'Muško', value: 'M' },
  { label: 'Žensko', value: 'F' },
];

export const categoryOptions = [
  { label: 'B1', value: 'B1' },
  { label: 'B', value: 'B' },
  { label: 'C1', value: 'C1' },
  { label: 'C', value: 'C' },
  { label: 'C1E', value: 'C1E' },
  { label: 'CE', value: 'CE' },
];

export const countries = [
  { name: 'Afganistan', code: 'AF' },
  { name: 'Albanija', code: 'AL' },
  { name: 'Alžir', code: 'DZ' },
  { name: 'Andora', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigva i Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenija', code: 'AM' },
  { name: 'Australija', code: 'AU' },
  { name: 'Austrija', code: 'AT' },
  { name: 'Azerbajdžan', code: 'AZ' },
  { name: 'Bahami', code: 'BS' },
  { name: 'Bahrein', code: 'BH' },
  { name: 'Bangladeš', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Bjelorusija', code: 'BY' },
  { name: 'Belgija', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Butan', code: 'BT' },
  { name: 'Bolivija', code: 'BO' },
  { name: 'Bosna i Hercegovina', code: 'BA' },
  { name: 'Bocvana', code: 'BW' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Brunej', code: 'BN' },
  { name: 'Bugarska', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Zelenortska Republika', code: 'CV' },
  { name: 'Kambodža', code: 'KH' },
  { name: 'Kamerun', code: 'CM' },
  { name: 'Kanada', code: 'CA' },
  { name: 'Srednjoafrička Republika', code: 'CF' },
  { name: 'Čad', code: 'TD' },
  { name: 'Čile', code: 'CL' },
  { name: 'Kina', code: 'CN' },
  { name: 'Kolumbija', code: 'CO' },
  { name: 'Komori', code: 'KM' },
  { name: 'Kongo (Republika Kongo)', code: 'CG' },
  { name: 'Kostarika', code: 'CR' },
  { name: 'Hrvatska', code: 'HR' },
  { name: 'Kuba', code: 'CU' },
  { name: 'Cipar', code: 'CY' },
  { name: 'Češka', code: 'CZ' },
  { name: 'Demokratska Republika Kongo', code: 'CD' },
  { name: 'Danska', code: 'DK' },
  { name: 'Džibuti', code: 'DJ' },
  { name: 'Dominika', code: 'DM' },
  { name: 'Dominikanska Republika', code: 'DO' },
  { name: 'Ekvador', code: 'EC' },
  { name: 'Egipat', code: 'EG' },
  { name: 'Salvador', code: 'SV' },
  { name: 'Ekvatorska Gvineja', code: 'GQ' },
  { name: 'Eritreja', code: 'ER' },
  { name: 'Estonija', code: 'EE' },
  { name: 'Esvatini', code: 'SZ' },
  { name: 'Etiopija', code: 'ET' },
  { name: 'Fidži', code: 'FJ' },
  { name: 'Finska', code: 'FI' },
  { name: 'Francuska', code: 'FR' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambija', code: 'GM' },
  { name: 'Gruzija', code: 'GE' },
  { name: 'Njemačka', code: 'DE' },
  { name: 'Gana', code: 'GH' },
  { name: 'Grčka', code: 'GR' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Gvatemala', code: 'GT' },
  { name: 'Gvineja', code: 'GN' },
  { name: 'Gvineja-Bissau', code: 'GW' },
  { name: 'Gvajana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Mađarska', code: 'HU' },
  { name: 'Island', code: 'IS' },
  { name: 'Indija', code: 'IN' },
  { name: 'Indonezija', code: 'ID' },
  { name: 'Iran', code: 'IR' },
  { name: 'Irak', code: 'IQ' },
  { name: 'Irska', code: 'IE' },
  { name: 'Izrael', code: 'IL' },
  { name: 'Italija', code: 'IT' },
  { name: 'Jamajka', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazahstan', code: 'KZ' },
  { name: 'Kenija', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Kuvajt', code: 'KW' },
  { name: 'Kirgistan', code: 'KG' },
  { name: 'Laos', code: 'LA' },
  { name: 'Latvija', code: 'LV' },
  { name: 'Libanon', code: 'LB' },
  { name: 'Lesoto', code: 'LS' },
  { name: 'Liberija', code: 'LR' },
  { name: 'Libija', code: 'LY' },
  { name: 'Lihtenštajn', code: 'LI' },
  { name: 'Litva', code: 'LT' },
  { name: 'Luksemburg', code: 'LU' },
  { name: 'Madagaskar', code: 'MG' },
  { name: 'Malavi', code: 'MW' },
  { name: 'Malezija', code: 'MY' },
  { name: 'Maldivi', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Maršalovi Otoci', code: 'MH' },
  { name: 'Mauritanija', code: 'MR' },
  { name: 'Mauricijus', code: 'MU' },
  { name: 'Meksiko', code: 'MX' },
  { name: 'Mikronezija', code: 'FM' },
  { name: 'Moldavija', code: 'MD' },
  { name: 'Monako', code: 'MC' },
  { name: 'Mongolija', code: 'MN' },
  { name: 'Crna Gora', code: 'ME' },
  { name: 'Maroko', code: 'MA' },
  { name: 'Mozambik', code: 'MZ' },
  { name: 'Mjanmar', code: 'MM' },
  { name: 'Namibija', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Nizozemska', code: 'NL' },
  { name: 'Novi Zeland', code: 'NZ' },
  { name: 'Nikaragva', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigerija', code: 'NG' },
  { name: 'Sjeverna Koreja', code: 'KP' },
  { name: 'Sjeverna Makedonija', code: 'MK' },
  { name: 'Norveška', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestina', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua Nova Gvineja', code: 'PG' },
  { name: 'Paragvaj', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Filipini', code: 'PH' },
  { name: 'Poljska', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Katar', code: 'QA' },
  { name: 'Rumunjska', code: 'RO' },
  { name: 'Rusija', code: 'RU' },
  { name: 'Ruanda', code: 'RW' },
  { name: 'Sveti Kristofor i Nevis', code: 'KN' },
  { name: 'Sveta Lucija', code: 'LC' },
  { name: 'Sveti Vincent i Grenadini', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome i Principe', code: 'ST' },
  { name: 'Saudijska Arabija', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Srbija', code: 'RS' },
  { name: 'Sejšeli', code: 'SC' },
  { name: 'Sijera Leone', code: 'SL' },
  { name: 'Singapur', code: 'SG' },
  { name: 'Slovačka', code: 'SK' },
  { name: 'Slovenija', code: 'SI' },
  { name: 'Solomonski Otoci', code: 'SB' },
  { name: 'Somalija', code: 'SO' },
  { name: 'Južnoafrička Republika', code: 'ZA' },
  { name: 'Južna Koreja', code: 'KR' },
  { name: 'Južni Sudan', code: 'SS' },
  { name: 'Španjolska', code: 'ES' },
  { name: 'Šri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Surinam', code: 'SR' },
  { name: 'Švedska', code: 'SE' },
  { name: 'Švicarska', code: 'CH' },
  { name: 'Sirija', code: 'SY' },
  { name: 'Tadžikistan', code: 'TJ' },
  { name: 'Tanzanija', code: 'TZ' },
  { name: 'Tajland', code: 'TH' },
  { name: 'Istočni Timor', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad i Tobago', code: 'TT' },
  { name: 'Tunis', code: 'TN' },
  { name: 'Turska', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukrajina', code: 'UA' },
  { name: 'Ujedinjeni Arapski Emirati', code: 'AE' },
  { name: 'Ujedinjeno Kraljevstvo', code: 'GB' },
  { name: 'Sjedinjene Američke Države', code: 'US' },
  { name: 'Urugvaj', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Vatikan', code: 'VA' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vijetnam', code: 'VN' },
  { name: 'Jemen', code: 'YE' },
  { name: 'Zambija', code: 'ZM' },
  { name: 'Zimbabve', code: 'ZW' },
];

export const countriesMap = keyBy(countries, 'code');

export function getCountryFromCode(countryCode: string) {
  return countriesMap[countryCode];
}

export const countryOptions = countries.map((c) => ({ value: c.code, label: c.name }));

const countryCodesEurope = [
  'AD',
  'AL',
  'AT',
  'AX',
  'BE',
  'BG',
  'BY',
  'CH',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'ES',
  'FI',
  'FO',
  'FR',
  'GB',
  'GG',
  'GI',
  'HR',
  'HU',
  'IE',
  'IM',
  'IS',
  'IT',
  'JE',
  'LI',
  'LT',
  'LU',
  'LV',
  'MC',
  'MD',
  'MK',
  'MT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RO',
  'RS',
  'SE',
  'SI',
  'SJ',
  'SK',
  'SM',
  'UA',
  'VA',
];

const countriesEurope = countries.filter((c) => countryCodesEurope.includes(c.code));
export const countryEuropeOptions = countriesEurope.map((c) => ({ value: c.code, label: c.name }));

export const formDefaultValues = {
  firstName: '',
  lastName: '',
  phoneNumber: '',
  email: '',
  position: '' as PositionEnum,
  governmentId: undefined as unknown as string,
  governmentIdExpiryDate: undefined as unknown as string,
  driverLicenceId: undefined as unknown as string,
  driverLicenceCategories: undefined as unknown as string[],
  adrExpiryDate: undefined as unknown as string,
  driverLicenceExpiryDate: undefined as unknown as string,
  professionalDriverLicenceExpiryDate: undefined as unknown as string,
  driverTachographCardId: undefined as unknown as string,
  driverTachographCardExpiryDate: undefined as unknown as string,
  nationality: undefined as unknown as string,
  contractExpiryDate: undefined as unknown as string,
  medicalExaminationExpiryDate: undefined as unknown as string,
  visaExpiryDate: undefined as unknown as string,
  code95ExpiryDate: undefined as unknown as string,
  dateOfBirth: undefined as unknown as string,
  residenceAddress: undefined as unknown as string,
};
