import type { Metadata } from "next";
import '@mantine/core/styles.css';
import "./globals.css";

import { MantineProvider } from '@mantine/core';
import { inter, playfairDisplaySc } from '@/ui/theme/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>CargoNavis</title>
      </head>
      <body className={`${inter.variable} ${playfairDisplaySc.variable} font-display`}>
        <MantineProvider>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
