import type { Metadata } from "next";
import "./globals.css";

import { inter, playfairDisplaySc } from '@/ui/theme/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>CargoNavis</title>
      </head>
      <body className={`${inter.variable} ${playfairDisplaySc.variable} font-display`}>{children}</body>
    </html>
  );
}
